/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const EvidenceType = IDL.Variant({
  'audio' : IDL.Null,
  'other' : IDL.Text,
  'video' : IDL.Null,
  'document' : IDL.Null,
  'photo' : IDL.Null,
  'screenshot' : IDL.Null,
});
export const EvidenceFile = IDL.Record({
  'id' : FileId,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'author' : UserId,
  'timestamp' : Timestamp,
  'evidenceType' : EvidenceType,
});
export const IncidentId = IDL.Nat;
export const IncidentStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'closureRequested' : IDL.Null,
});
export const Incident = IDL.Record({
  'id' : IncidentId,
  'status' : IncidentStatus,
  'title' : IDL.Text,
  'criminalActivityReportNumber' : IDL.Text,
  'description' : IDL.Text,
  'author' : UserId,
  'timestamp' : Timestamp,
  'evidenceIds' : IDL.Vec(FileId),
});
export const PoliceDepartment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'website' : IDL.Text,
  'isVerified' : IDL.Bool,
  'addedBy' : UserId,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const StalkerProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'notes' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserSettings = IDL.Record({
  'language' : IDL.Text,
  'motivationalVideo' : IDL.Opt(ExternalBlob),
  'toneStyle' : IDL.Variant({
    'assertiveWomen' : IDL.Null,
    'directSafety' : IDL.Null,
    'balanced' : IDL.Null,
  }),
  'visualTheme' : IDL.Variant({
    'redFeminineBold' : IDL.Null,
    'default' : IDL.Null,
    'womenSafety' : IDL.Null,
  }),
});
export const VictimSurvivorInfo = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'contactInfo' : IDL.Opt(IDL.Text),
  'additionalNotes' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'emergencyContact' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllEvidence' : IDL.Func([], [IDL.Vec(EvidenceFile)], ['query']),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getAllPoliceDepartments' : IDL.Func(
      [],
      [IDL.Vec(PoliceDepartment)],
      ['query'],
    ),
  'getCallerEvidence' : IDL.Func([], [IDL.Vec(EvidenceFile)], ['query']),
  'getCallerIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getCallerPoliceDepartments' : IDL.Func(
      [],
      [IDL.Vec(PoliceDepartment)],
      ['query'],
    ),
  'getCallerStalkerProfiles' : IDL.Func(
      [],
      [IDL.Vec(StalkerProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'getCallerVictimSurvivorInfo' : IDL.Func(
      [],
      [IDL.Opt(VictimSurvivorInfo)],
      ['query'],
    ),
  'getEvidenceById' : IDL.Func([FileId], [IDL.Opt(EvidenceFile)], ['query']),
  'getIncidentById' : IDL.Func([IncidentId], [IDL.Opt(Incident)], ['query']),
  'getUserIncidents' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Incident)],
      ['query'],
    ),
  'getUserPoliceDepartments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PoliceDepartment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedPoliceDepartments' : IDL.Func(
      [],
      [IDL.Vec(PoliceDepartment)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportIncident' : IDL.Func([IDL.Text, IDL.Text], [Incident], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePoliceDepartment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PoliceDepartment],
      [],
    ),
  'saveStalkerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [StalkerProfile],
      [],
    ),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
  'saveVictimSurvivorInfo' : IDL.Func([VictimSurvivorInfo], [], []),
  'setMotivationalVideo' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'uploadEvidence' : IDL.Func(
      [IDL.Text, IDL.Text, EvidenceType, ExternalBlob, IncidentId],
      [EvidenceFile],
      [],
    ),
  'verifyPoliceDepartment' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const EvidenceType = IDL.Variant({
    'audio' : IDL.Null,
    'other' : IDL.Text,
    'video' : IDL.Null,
    'document' : IDL.Null,
    'photo' : IDL.Null,
    'screenshot' : IDL.Null,
  });
  const EvidenceFile = IDL.Record({
    'id' : FileId,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'author' : UserId,
    'timestamp' : Timestamp,
    'evidenceType' : EvidenceType,
  });
  const IncidentId = IDL.Nat;
  const IncidentStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'closureRequested' : IDL.Null,
  });
  const Incident = IDL.Record({
    'id' : IncidentId,
    'status' : IncidentStatus,
    'title' : IDL.Text,
    'criminalActivityReportNumber' : IDL.Text,
    'description' : IDL.Text,
    'author' : UserId,
    'timestamp' : Timestamp,
    'evidenceIds' : IDL.Vec(FileId),
  });
  const PoliceDepartment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'website' : IDL.Text,
    'isVerified' : IDL.Bool,
    'addedBy' : UserId,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StalkerProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'notes' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserSettings = IDL.Record({
    'language' : IDL.Text,
    'motivationalVideo' : IDL.Opt(ExternalBlob),
    'toneStyle' : IDL.Variant({
      'assertiveWomen' : IDL.Null,
      'directSafety' : IDL.Null,
      'balanced' : IDL.Null,
    }),
    'visualTheme' : IDL.Variant({
      'redFeminineBold' : IDL.Null,
      'default' : IDL.Null,
      'womenSafety' : IDL.Null,
    }),
  });
  const VictimSurvivorInfo = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'contactInfo' : IDL.Opt(IDL.Text),
    'additionalNotes' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'emergencyContact' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllEvidence' : IDL.Func([], [IDL.Vec(EvidenceFile)], ['query']),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getAllPoliceDepartments' : IDL.Func(
        [],
        [IDL.Vec(PoliceDepartment)],
        ['query'],
      ),
    'getCallerEvidence' : IDL.Func([], [IDL.Vec(EvidenceFile)], ['query']),
    'getCallerIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getCallerPoliceDepartments' : IDL.Func(
        [],
        [IDL.Vec(PoliceDepartment)],
        ['query'],
      ),
    'getCallerStalkerProfiles' : IDL.Func(
        [],
        [IDL.Vec(StalkerProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'getCallerVictimSurvivorInfo' : IDL.Func(
        [],
        [IDL.Opt(VictimSurvivorInfo)],
        ['query'],
      ),
    'getEvidenceById' : IDL.Func([FileId], [IDL.Opt(EvidenceFile)], ['query']),
    'getIncidentById' : IDL.Func([IncidentId], [IDL.Opt(Incident)], ['query']),
    'getUserIncidents' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Incident)],
        ['query'],
      ),
    'getUserPoliceDepartments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PoliceDepartment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedPoliceDepartments' : IDL.Func(
        [],
        [IDL.Vec(PoliceDepartment)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportIncident' : IDL.Func([IDL.Text, IDL.Text], [Incident], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePoliceDepartment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PoliceDepartment],
        [],
      ),
    'saveStalkerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [StalkerProfile],
        [],
      ),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
    'saveVictimSurvivorInfo' : IDL.Func([VictimSurvivorInfo], [], []),
    'setMotivationalVideo' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'uploadEvidence' : IDL.Func(
        [IDL.Text, IDL.Text, EvidenceType, ExternalBlob, IncidentId],
        [EvidenceFile],
        [],
      ),
    'verifyPoliceDepartment' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };