/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EvidenceFile {
  'id' : FileId,
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
  'author' : UserId,
  'timestamp' : Timestamp,
  'evidenceType' : EvidenceType,
}
export type EvidenceType = { 'audio' : null } |
  { 'other' : string } |
  { 'video' : null } |
  { 'document' : null } |
  { 'photo' : null } |
  { 'screenshot' : null };
export type ExternalBlob = Uint8Array;
export type FileId = bigint;
export interface Incident {
  'id' : IncidentId,
  'status' : IncidentStatus,
  'title' : string,
  'criminalActivityReportNumber' : string,
  'description' : string,
  'author' : UserId,
  'timestamp' : Timestamp,
  'evidenceIds' : Array<FileId>,
}
export type IncidentId = bigint;
export type IncidentStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'closureRequested' : null };
export interface PoliceDepartment {
  'id' : bigint,
  'name' : string,
  'website' : string,
  'isVerified' : boolean,
  'addedBy' : UserId,
  'address' : string,
  'phone' : string,
}
export interface StalkerProfile {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'notes' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'language' : string,
  'motivationalVideo' : [] | [ExternalBlob],
  'toneStyle' : { 'assertiveWomen' : null } |
    { 'directSafety' : null } |
    { 'balanced' : null },
  'visualTheme' : { 'redFeminineBold' : null } |
    { 'default' : null } |
    { 'womenSafety' : null },
}
export interface VictimSurvivorInfo {
  'age' : [] | [bigint],
  'contactInfo' : [] | [string],
  'additionalNotes' : [] | [string],
  'name' : [] | [string],
  'emergencyContact' : [] | [string],
  'gender' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllEvidence' : ActorMethod<[], Array<EvidenceFile>>,
  'getAllIncidents' : ActorMethod<[], Array<Incident>>,
  'getAllPoliceDepartments' : ActorMethod<[], Array<PoliceDepartment>>,
  'getCallerEvidence' : ActorMethod<[], Array<EvidenceFile>>,
  'getCallerIncidents' : ActorMethod<[], Array<Incident>>,
  'getCallerPoliceDepartments' : ActorMethod<[], Array<PoliceDepartment>>,
  'getCallerStalkerProfiles' : ActorMethod<[], Array<StalkerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getCallerVictimSurvivorInfo' : ActorMethod<[], [] | [VictimSurvivorInfo]>,
  'getEvidenceById' : ActorMethod<[FileId], [] | [EvidenceFile]>,
  'getIncidentById' : ActorMethod<[IncidentId], [] | [Incident]>,
  'getUserIncidents' : ActorMethod<[Principal], Array<Incident>>,
  'getUserPoliceDepartments' : ActorMethod<
    [Principal],
    Array<PoliceDepartment>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedPoliceDepartments' : ActorMethod<[], Array<PoliceDepartment>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportIncident' : ActorMethod<[string, string], Incident>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePoliceDepartment' : ActorMethod<
    [string, string, string, string],
    PoliceDepartment
  >,
  'saveStalkerProfile' : ActorMethod<[string, string, string], StalkerProfile>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
  'saveVictimSurvivorInfo' : ActorMethod<[VictimSurvivorInfo], undefined>,
  'setMotivationalVideo' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'uploadEvidence' : ActorMethod<
    [string, string, EvidenceType, ExternalBlob, IncidentId],
    EvidenceFile
  >,
  'verifyPoliceDepartment' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];