/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Timestamp = bigint;
export type IncidentId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Incident {
    id: IncidentId;
    status: IncidentStatus;
    title: string;
    criminalActivityReportNumber: string;
    description: string;
    author: UserId;
    timestamp: Timestamp;
    evidenceIds: Array<FileId>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type EvidenceType = {
    __kind__: "audio";
    audio: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "video";
    video: null;
} | {
    __kind__: "document";
    document: null;
} | {
    __kind__: "photo";
    photo: null;
} | {
    __kind__: "screenshot";
    screenshot: null;
};
export type UserId = Principal;
export interface VictimSurvivorInfo {
    age?: bigint;
    contactInfo?: string;
    additionalNotes?: string;
    name?: string;
    emergencyContact?: string;
    gender?: string;
}
export interface UserSettings {
    language: string;
    toneStyle: Variant_assertiveWomen_directSafety_balanced;
    visualTheme: Variant_redFeminineBold_default_womenSafety;
}
export interface StalkerProfile {
    id: bigint;
    name: string;
    description: string;
    notes: string;
}
export type FileId = bigint;
export interface EvidenceFile {
    id: FileId;
    title: string;
    file: ExternalBlob;
    description: string;
    author: UserId;
    timestamp: Timestamp;
    evidenceType: EvidenceType;
}
export interface PoliceDepartment {
    id: bigint;
    name: string;
    website: string;
    isVerified: boolean;
    addedBy: UserId;
    address: string;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export enum IncidentStatus {
    closed = "closed",
    open = "open",
    closureRequested = "closureRequested"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_assertiveWomen_directSafety_balanced {
    assertiveWomen = "assertiveWomen",
    directSafety = "directSafety",
    balanced = "balanced"
}
export enum Variant_redFeminineBold_default_womenSafety {
    redFeminineBold = "redFeminineBold",
    default_ = "default",
    womenSafety = "womenSafety"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllEvidence(): Promise<Array<EvidenceFile>>;
    getAllIncidents(): Promise<Array<Incident>>;
    getAllPoliceDepartments(): Promise<Array<PoliceDepartment>>;
    getCallerEvidence(): Promise<Array<EvidenceFile>>;
    getCallerIncidents(): Promise<Array<Incident>>;
    getCallerPoliceDepartments(): Promise<Array<PoliceDepartment>>;
    getCallerStalkerProfiles(): Promise<Array<StalkerProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerUserSettings(): Promise<UserSettings | null>;
    getCallerVictimSurvivorInfo(): Promise<VictimSurvivorInfo | null>;
    getEvidenceById(id: FileId): Promise<EvidenceFile | null>;
    getIncidentById(id: IncidentId): Promise<Incident | null>;
    getUserIncidents(user: Principal): Promise<Array<Incident>>;
    getUserPoliceDepartments(user: Principal): Promise<Array<PoliceDepartment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerifiedPoliceDepartments(): Promise<Array<PoliceDepartment>>;
    isCallerAdmin(): Promise<boolean>;
    reportIncident(title: string, description: string): Promise<Incident>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePoliceDepartment(name: string, address: string, phone: string, website: string): Promise<PoliceDepartment>;
    saveStalkerProfile(name: string, description: string, notes: string): Promise<StalkerProfile>;
    saveUserSettings(settings: UserSettings): Promise<void>;
    saveVictimSurvivorInfo(info: VictimSurvivorInfo): Promise<void>;
    uploadEvidence(title: string, description: string, evidenceType: EvidenceType, file: ExternalBlob, incidentId: IncidentId): Promise<EvidenceFile>;
    verifyPoliceDepartment(deptId: bigint): Promise<void>;
}
import type { EvidenceFile as _EvidenceFile, EvidenceType as _EvidenceType, ExternalBlob as _ExternalBlob, FileId as _FileId, Incident as _Incident, IncidentId as _IncidentId, IncidentStatus as _IncidentStatus, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserSettings as _UserSettings, VictimSurvivorInfo as _VictimSurvivorInfo, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllEvidence(): Promise<Array<EvidenceFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvidence();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvidence();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidents();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidents();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPoliceDepartments(): Promise<Array<PoliceDepartment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPoliceDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPoliceDepartments();
            return result;
        }
    }
    async getCallerEvidence(): Promise<Array<EvidenceFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerEvidence();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerEvidence();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIncidents();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIncidents();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPoliceDepartments(): Promise<Array<PoliceDepartment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPoliceDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPoliceDepartments();
            return result;
        }
    }
    async getCallerStalkerProfiles(): Promise<Array<StalkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStalkerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStalkerProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserSettings(): Promise<UserSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserSettings();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserSettings();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerVictimSurvivorInfo(): Promise<VictimSurvivorInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerVictimSurvivorInfo();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerVictimSurvivorInfo();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceById(arg0: FileId): Promise<EvidenceFile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceById(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceById(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidentById(arg0: IncidentId): Promise<Incident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentById(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentById(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserIncidents(arg0: Principal): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserIncidents(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserIncidents(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPoliceDepartments(arg0: Principal): Promise<Array<PoliceDepartment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPoliceDepartments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPoliceDepartments(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedPoliceDepartments(): Promise<Array<PoliceDepartment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedPoliceDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedPoliceDepartments();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reportIncident(arg0: string, arg1: string): Promise<Incident> {
        if (this.processError) {
            try {
                const result = await this.actor.reportIncident(arg0, arg1);
                return from_candid_Incident_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportIncident(arg0, arg1);
            return from_candid_Incident_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePoliceDepartment(arg0: string, arg1: string, arg2: string, arg3: string): Promise<PoliceDepartment> {
        if (this.processError) {
            try {
                const result = await this.actor.savePoliceDepartment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePoliceDepartment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveStalkerProfile(arg0: string, arg1: string, arg2: string): Promise<StalkerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStalkerProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStalkerProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async saveUserSettings(arg0: UserSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(to_candid_UserSettings_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(to_candid_UserSettings_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveVictimSurvivorInfo(arg0: VictimSurvivorInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVictimSurvivorInfo(to_candid_VictimSurvivorInfo_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVictimSurvivorInfo(to_candid_VictimSurvivorInfo_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadEvidence(arg0: string, arg1: string, arg2: EvidenceType, arg3: ExternalBlob, arg4: IncidentId): Promise<EvidenceFile> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEvidence(arg0, arg1, to_candid_EvidenceType_n41(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n43(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_EvidenceFile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEvidence(arg0, arg1, to_candid_EvidenceType_n41(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n43(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_EvidenceFile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyPoliceDepartment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPoliceDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPoliceDepartment(arg0);
            return result;
        }
    }
}
async function from_candid_EvidenceFile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceFile): Promise<EvidenceFile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceType): EvidenceType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IncidentStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentStatus): IncidentStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Incident_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Incident): Incident {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_VictimSurvivorInfo_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VictimSurvivorInfo): VictimSurvivorInfo {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettings]): UserSettings | null {
    return value.length === 0 ? null : from_candid_UserSettings_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VictimSurvivorInfo]): VictimSurvivorInfo | null {
    return value.length === 0 ? null : from_candid_VictimSurvivorInfo_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EvidenceFile]): Promise<EvidenceFile | null> {
    return value.length === 0 ? null : await from_candid_EvidenceFile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Incident]): Incident | null {
    return value.length === 0 ? null : from_candid_Incident_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FileId;
    title: string;
    file: _ExternalBlob;
    description: string;
    author: _UserId;
    timestamp: _Timestamp;
    evidenceType: _EvidenceType;
}): Promise<{
    id: FileId;
    title: string;
    file: ExternalBlob;
    description: string;
    author: UserId;
    timestamp: Timestamp;
    evidenceType: EvidenceType;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.file),
        description: value.description,
        author: value.author,
        timestamp: value.timestamp,
        evidenceType: from_candid_EvidenceType_n14(_uploadFile, _downloadFile, value.evidenceType)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IncidentId;
    status: _IncidentStatus;
    title: string;
    criminalActivityReportNumber: string;
    description: string;
    author: _UserId;
    timestamp: _Timestamp;
    evidenceIds: Array<_FileId>;
}): {
    id: IncidentId;
    status: IncidentStatus;
    title: string;
    criminalActivityReportNumber: string;
    description: string;
    author: UserId;
    timestamp: Timestamp;
    evidenceIds: Array<FileId>;
} {
    return {
        id: value.id,
        status: from_candid_IncidentStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        criminalActivityReportNumber: value.criminalActivityReportNumber,
        description: value.description,
        author: value.author,
        timestamp: value.timestamp,
        evidenceIds: value.evidenceIds
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    language: string;
    toneStyle: {
        assertiveWomen: null;
    } | {
        directSafety: null;
    } | {
        balanced: null;
    };
    visualTheme: {
        redFeminineBold: null;
    } | {
        default: null;
    } | {
        womenSafety: null;
    };
}): {
    language: string;
    toneStyle: Variant_assertiveWomen_directSafety_balanced;
    visualTheme: Variant_redFeminineBold_default_womenSafety;
} {
    return {
        language: value.language,
        toneStyle: from_candid_variant_n27(_uploadFile, _downloadFile, value.toneStyle),
        visualTheme: from_candid_variant_n28(_uploadFile, _downloadFile, value.visualTheme)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    contactInfo: [] | [string];
    additionalNotes: [] | [string];
    name: [] | [string];
    emergencyContact: [] | [string];
    gender: [] | [string];
}): {
    age?: bigint;
    contactInfo?: string;
    additionalNotes?: string;
    name?: string;
    emergencyContact?: string;
    gender?: string;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        contactInfo: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.contactInfo)),
        additionalNotes: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.additionalNotes)),
        name: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.name)),
        emergencyContact: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.emergencyContact)),
        gender: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.gender))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    other: string;
} | {
    video: null;
} | {
    document: null;
} | {
    photo: null;
} | {
    screenshot: null;
}): {
    __kind__: "audio";
    audio: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "video";
    video: null;
} | {
    __kind__: "document";
    document: null;
} | {
    __kind__: "photo";
    photo: null;
} | {
    __kind__: "screenshot";
    screenshot: null;
} {
    return "audio" in value ? {
        __kind__: "audio",
        audio: value.audio
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "video" in value ? {
        __kind__: "video",
        video: value.video
    } : "document" in value ? {
        __kind__: "document",
        document: value.document
    } : "photo" in value ? {
        __kind__: "photo",
        photo: value.photo
    } : "screenshot" in value ? {
        __kind__: "screenshot",
        screenshot: value.screenshot
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    closureRequested: null;
}): IncidentStatus {
    return "closed" in value ? IncidentStatus.closed : "open" in value ? IncidentStatus.open : "closureRequested" in value ? IncidentStatus.closureRequested : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assertiveWomen: null;
} | {
    directSafety: null;
} | {
    balanced: null;
}): Variant_assertiveWomen_directSafety_balanced {
    return "assertiveWomen" in value ? Variant_assertiveWomen_directSafety_balanced.assertiveWomen : "directSafety" in value ? Variant_assertiveWomen_directSafety_balanced.directSafety : "balanced" in value ? Variant_assertiveWomen_directSafety_balanced.balanced : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redFeminineBold: null;
} | {
    default: null;
} | {
    womenSafety: null;
}): Variant_redFeminineBold_default_womenSafety {
    return "redFeminineBold" in value ? Variant_redFeminineBold_default_womenSafety.redFeminineBold : "default" in value ? Variant_redFeminineBold_default_womenSafety.default : "womenSafety" in value ? Variant_redFeminineBold_default_womenSafety.womenSafety : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvidenceFile>): Promise<Array<EvidenceFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EvidenceFile_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Incident>): Array<Incident> {
    return value.map((x)=>from_candid_Incident_n17(_uploadFile, _downloadFile, x));
}
function to_candid_EvidenceType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceType): _EvidenceType {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserSettings_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserSettings): _UserSettings {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_VictimSurvivorInfo_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VictimSurvivorInfo): _VictimSurvivorInfo {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    language: string;
    toneStyle: Variant_assertiveWomen_directSafety_balanced;
    visualTheme: Variant_redFeminineBold_default_womenSafety;
}): {
    language: string;
    toneStyle: {
        assertiveWomen: null;
    } | {
        directSafety: null;
    } | {
        balanced: null;
    };
    visualTheme: {
        redFeminineBold: null;
    } | {
        default: null;
    } | {
        womenSafety: null;
    };
} {
    return {
        language: value.language,
        toneStyle: to_candid_variant_n37(_uploadFile, _downloadFile, value.toneStyle),
        visualTheme: to_candid_variant_n38(_uploadFile, _downloadFile, value.visualTheme)
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    contactInfo?: string;
    additionalNotes?: string;
    name?: string;
    emergencyContact?: string;
    gender?: string;
}): {
    age: [] | [bigint];
    contactInfo: [] | [string];
    additionalNotes: [] | [string];
    name: [] | [string];
    emergencyContact: [] | [string];
    gender: [] | [string];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        contactInfo: value.contactInfo ? candid_some(value.contactInfo) : candid_none(),
        additionalNotes: value.additionalNotes ? candid_some(value.additionalNotes) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        emergencyContact: value.emergencyContact ? candid_some(value.emergencyContact) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none()
    };
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_assertiveWomen_directSafety_balanced): {
    assertiveWomen: null;
} | {
    directSafety: null;
} | {
    balanced: null;
} {
    return value == Variant_assertiveWomen_directSafety_balanced.assertiveWomen ? {
        assertiveWomen: null
    } : value == Variant_assertiveWomen_directSafety_balanced.directSafety ? {
        directSafety: null
    } : value == Variant_assertiveWomen_directSafety_balanced.balanced ? {
        balanced: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_redFeminineBold_default_womenSafety): {
    redFeminineBold: null;
} | {
    default: null;
} | {
    womenSafety: null;
} {
    return value == Variant_redFeminineBold_default_womenSafety.redFeminineBold ? {
        redFeminineBold: null
    } : value == Variant_redFeminineBold_default_womenSafety.default ? {
        default_: null
    } : value == Variant_redFeminineBold_default_womenSafety.womenSafety ? {
        womenSafety: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "audio";
    audio: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "video";
    video: null;
} | {
    __kind__: "document";
    document: null;
} | {
    __kind__: "photo";
    photo: null;
} | {
    __kind__: "screenshot";
    screenshot: null;
}): {
    audio: null;
} | {
    other: string;
} | {
    video: null;
} | {
    document: null;
} | {
    photo: null;
} | {
    screenshot: null;
} {
    return value.__kind__ === "audio" ? {
        audio: value.audio
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "video" ? {
        video: value.video
    } : value.__kind__ === "document" ? {
        document: value.document
    } : value.__kind__ === "photo" ? {
        photo: value.photo
    } : value.__kind__ === "screenshot" ? {
        screenshot: value.screenshot
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
